port: 8080
appname: Chatapp
dbtype: mysql
mysql:
  dbip: 127.0.0.1:3306
  dbname: chatapp
  dbuser: root
  dbpass: 12345678
  dbretrycount: 5
  migratedbuser: root
  migratedbpass: 12345678
migratedb: true
continueaftermigrate: true
rabbitmq:
  user: user
  password: password
